#CONFIG
SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 1080
FPS = 60

#ASTEROID CONSTS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.0  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#PLAYER CONSTS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 200
SHOT_RADIUS = 4
SHOT_TTL = 4.5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

#PARALLAX
NUM_STARS = 70
PARALLAX_SPEEDS = [16.0, 20.5, 30.0] 